# Made by: Arthur Aguiar a,k,a: asepulve (13/08/2024)

# The .env file is loaded from the same directory in which the docker-compole.yml file is

services:
  nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "8080:80" # The port 80 in the hostmachine is busy
        - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    ports:
        - "9000:9000"
 #   env_file:
 #      - path: /home/asepulve/Desktop -> path to the .env
 #        required: true # default
    restart: on-failure

