# Made by: Arthur Aguiar a,k,a: asepulve (13/08/2024)

services:
  nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "8080:80"
#- "443:443"
    restart: on-failure

#env_path:
#        -path: ./.env
