# Made by: Arthur Aguiar a,k,a: asepulve (13/08/2024)

# The .env file is loaded from the same directory in which the docker-compole.yml file is


# NGINX: (Nginx)
#
services:
  nginx:
    container_name: nginx
    build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
    ports:
        - "443:443"
    networks:
        - inception
    restart: on-failure

# Wordpress: (Wordpress+php-fpm) 
#
  wordpress:
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    expose:
        - "9000"
    ports:
        - "9000:9000"
    networks:
        - inception
    restart: on-failure


networks:
    inception:
        driver: bridge # Eliminates the need for routing between different network segments.
        name: inception # Forces the name of the network ot be inception
