FROM debian:bullseye


#Link to the guide:
# docs.nginx.com/nginx/admin-guide/installing-nginx/installing-nginx-open-source/#installing-prebuilt-debian-packages

# Update the Debian repository information:
RUN sudo apt-get update

# Install the NGINX Open Source package:
RUN sudo apt-get install -y nginx




